print('')
print('PET SHOP - REALEZA PET')
print('')
print('Olá, tudo bem?')
print('')
print('Antes de tudo, preciso saber de qual serviço você quer informações:')
print('1 - tosa porte pequeno.')
print('2 - tosa porte médio.')
print('3 - tosa porte grande.')
print('4 - banho.')
respservico = input('RESPONDA AGORA:')
um = input('O valor da tosa de porte pequeno é de R$50,00')
