print ("Olá, boa tarde! Gostaria que respondesse o questinonario abaixo para que o médico tenha uma pré avaliação do seu caso. Responda as perguntas abaixo:")
print('')
nome=input('Eu gostaria de saber o seu nome completo ? ')
print('')
print ('Certo, Obrigado ', nome)
print('')
idade1 =input('Quantos anos você tem? ')
idade=input('Qual a sua data de nascimento ? ')
peso=input('Qual é o seu peso ? ') 
queixa=input('O que você vem sentindo ? Ex: Tontura, enjoo, pressão baixa, etc: ')
historico=input('Tem histórico do mesmo caso na familia ? ')
dias=input('Há quantos dias você está sentindo esses sintomas ? ')
drogas=input('Você usa drogas ou álcool ? ')
frequencia=input('Você faz um check-up médico com frequencia? ')
medicamento=input('Nas últimas 24 horas, que diferentes tipos  de medicamentos você tomou? Qual?')
print('')
print('RESULTADO: ')
print ('Seu nome é ' + nome)
print ('Sua idade é de ' + idade1)
print ('Sua data de nasc é ' + idade)
print ('Você pesa ' + peso)
print ('Histórico familiar ' + historico)
print ('Há quantos dias vem sentindo os sintomas ' + dias)
print ('Usa drogas ou consome alcool ? ' + drogas)
print ('Faz check up médico frequentemente? ' + frequencia)
print ('Medicamento que usa ' + medicamento)



